# AppVeyor documentation https://www.appveyor.com/docs

version: '{build}'

image:
- Ubuntu
- Visual Studio 2019

pull_requests:
  # Do not increment build number for pull requests
  do_not_increment_build_number: true

nuget:
  # Do not publish for pull requests
  disable_publish_on_pr: true

environment:
  # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true

build_script:
- sh: sudo apt-get update
- sh: sudo apt-get install -y dotnet-sdk-2.2
- cmd: choco install dotnetcore-sdk --no-progress --confirm --version 2.2.402
- pwsh: dotnet tool install --global Cake.Tool
- pwsh: dotnet cake --target=Build
- pwsh: dotnet cake --target=InstallDeveloperCertificate
- pwsh: dotnet cake --target=Test
- pwsh: dotnet cake --target=Pack

test: off

artifacts:
- name: NuGet Packages
  path: ./Artifacts/**/*.nupkg
- name: NuGet Symbol Packages
  path: ./Artifacts/**/*.snupkg
- name: xUnit Test Results
  path: ./Artifacts/**/*.xml
