# AppVeyor documentation https://www.appveyor.com/docs

version: '{build}'

image:
  - Visual Studio 2017
install:
- appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

pull_requests:
  # Do not increment build number for pull requests
  do_not_increment_build_number: true

environment:
  # Run sh scripts on Linux
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  # The My-Get API key to publish the VSIX
  MyGetApiKey:
    secure: aunGGWt32irQiOTX2wIO6e2Y5Ga0girA3xSUsmQv6E9d6ohHdbK5HJpXpmxW9QM3

build_script:
- ps: choco install dotnetcore-sdk --no-progress --confirm --version 2.2.0
- ps: .\build.ps1

test: off

artifacts:
# Store NuGet packages
- path: .\Artifacts\**\*.nupkg
  name: NuGet
# Store xUnit Test Results
- path: .\Artifacts\**\*.trx
  name: xUnit Test Results

deploy:
# Publish MyGet packages
- provider: NuGet
  name: development
  server: https://www.myget.org/F/dotnet-boxed/api/v2
  api_key:
    secure: aunGGWt32irQiOTX2wIO6e2Y5Ga0girA3xSUsmQv6E9d6ohHdbK5HJpXpmxW9QM3
  on:
    # Only publish from the master branch
    branch: master
# Publish NuGet packages
- provider: NuGet
  name: production
  api_key:
    secure: 73eFUWSfho6pxCy1VRP1H0AYh/SFiyEREV+/ATcoj0I+sSH9dec/WXs6H2Jy5vlS
  on:
    # Only publish from the master branch
    branch: master
    # Only publish if the trigger was a Git tag
    # git tag v0.1.0-beta
    # git push origin --tags
    appveyor_repo_tag: true